# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_budget', '0002_auto_20160908_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='next_due_date',
            field=models.DateField(default=models.DateField(), null=True),
        ),
    ]
